### ISSUE TITLE
TacoTrucks.Party

### ISSUE THREAD

**Issue by kielni** [DevProgress/projects#1]
- TacoTrucks.Party
- Make #TacoTrucksOnEveryCorner a reality. Sponsor a taco truck on the map and share with friends. Clicking Sponsor goes to the HRC donate page with $10 pre-selected.
- Google Maps, client-side JavaScript, Firebase
- launched!
- https://tacotrucks.party

**Comment by kielni** [comment]
![TacoTrucks.party](https://cloud.githubusercontent.com/assets/1649528/18595294/e25965a2-7bf8-11e6-968e-a5f1ed36f7d6.png)

**Comment by jillh510** [comment]
Can this issue be closed?
