### ISSUE TITLE
Add candidatebot to projects gallery

### ISSUE THREAD

**Issue by whereistanya** [DevProgress/projects#2]
- Name: candidatebot
- Description: a commandline tool to create simple d wikipedia pages for down-ticket candidates who don't have them
- Stack: python
- Repo: https://github.com/DevProgress/candidatebot/
- Status: in progress. Currently reading two datas sources (http://www.fec.gov/data/CandidateSummary.do and https://en.wikipedia.org/wiki/United_States_House_of_Representatives_elections,_2016) and creating wikipidia stub pages on our test mediawiki instance. Needs more data sources, cleaner data, and a lot of wikipedia style.

**Comment by jillh510** [comment]
Can this issue be closed?
