### ISSUE TITLE
Deploy fails on missing .git

### ISSUE THREAD

**Issue by wboykinm** [DevProgress/projects#28]
I suspect `gulp deploy` is built around someone's local config, because I get 

```
| ~/github/projects @ vtcraghead2 (wboykinm) 
| => gulp deploy
[11:08:54] Using gulpfile ~/github/projects/gulpfile.js
[11:08:54] Starting 'deploy'...
[11:08:55] 'deploy' errored after 143 ms
[11:08:55] Error in plugin 'gulp-gh-pages'
Message:
    ENOENT: no such file or directory, open '.publish/.git/HEAD'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: .publish/.git/HEAD
```

It's odd to see that the `gh-pages` branch shares no history with `master`, so I'm not comfortable manually pushing the changes resulting from my merge of PR: #27

**Comment by mattrothenberg** [comment]
@wboykinm Feel free to put together a better script for deploying to `gh-pages`!

The step recommended here has solved the issue for other users who've run in to this.

https://github.com/shinnn/gulp-gh-pages/issues/87

**Comment by wboykinm** [comment]
@mattrothenberg I wouldn't dare write a new publishing pipeline; my usual method is just pushing to `gh-pages` directly :)

But that linked fix did the trick. Thanks!

**Comment by mattrothenberg** [comment]
Awesome, glad it worked @wboykinm :+1:
