### ISSUE TITLE
Add events map

### ISSUE THREAD

**Issue by wboykinm** [DevProgress/projects#4]
- Name: HRC Events map
- Description: Find events and volunteer opportunities with the Clinton campaign in your area
- Stack: javascript
- Status: **live!!!**
- URL: https://devprogress.us/hrc-events/
- img: https://c1.staticflickr.com/9/8037/29342218640_8429488332_o.png
- gif: https://www.dropbox.com/s/d7xsbcl8p4grjzi/hrc4.gif?dl=0
- repo: https://github.com/DevProgress/hrc-events

**Comment by jillh510** [comment]
Can this issue be closed now?

**Comment by wboykinm** [comment]
Looks good to me. I see it [on the site](https://devprogress.us/projects/).
