### ISSUE TITLE
Add Images for live projects

### ISSUE THREAD

**Issue by rschroed** [DevProgress/projects#8]
Update: these are on 'DevProgress Project Images' dropbox shared folder

here's images for the 'live' projects that don't have them 

![dtv-projects-events](https://cloud.githubusercontent.com/assets/12657/18649082/7133943e-7e72-11e6-8a6e-f8ac16bc9ac0.jpg)
![dtv-projects-gcal-bridge](https://cloud.githubusercontent.com/assets/12657/18649086/7163aa70-7e72-11e6-8e88-597dbf6aa34d.jpg)
![dtv-projects-laborfh](https://cloud.githubusercontent.com/assets/12657/18649084/71595a2a-7e72-11e6-8600-a64ffdf9148e.jpg)
![dtv-projects-lfh](https://cloud.githubusercontent.com/assets/12657/18649085/71599422-7e72-11e6-9ffa-d858f2886b0e.jpg)
![dtv-projects-wfh](https://cloud.githubusercontent.com/assets/12657/18649083/7157473a-7e72-11e6-8a54-af7fdc2e60cb.jpg)

**Comment by rschroed** [comment]
![dtv-projects-debate-bingo](https://cloud.githubusercontent.com/assets/12657/18656292/c4d6bc6a-7ea4-11e6-86a7-7d10ea768bb6.jpg)
![dtv-projects-dtv](https://cloud.githubusercontent.com/assets/12657/18656293/c4d8cdfc-7ea4-11e6-9071-33597c34f5a4.jpg)
![dtv-projects-gcal-bridge](https://cloud.githubusercontent.com/assets/12657/18656291/c4d67e94-7ea4-11e6-8d28-ca95f715aeec.jpg)
![dtv-projects-hbnb](https://cloud.githubusercontent.com/assets/12657/18656294/c4da9bb4-7ea4-11e6-9e7f-be5911db3dcd.jpg)

**Comment by rschroed** [comment]
![dtv-projects-i-like-hillary](https://cloud.githubusercontent.com/assets/12657/18656304/d467a7d4-7ea4-11e6-98a2-f787786037b9.jpg)

**Comment by robmyre** [comment]
![cvs_simple_search](https://cloud.githubusercontent.com/assets/21959358/18681622/e39d078e-7f36-11e6-9830-c5f22dfd72b9.jpg)

**Comment by robmyre** [comment]
![devprogress_us](https://cloud.githubusercontent.com/assets/21959358/18681647/fd8682d8-7f36-11e6-85ed-1ce5917d6617.jpg)

**Comment by robmyre** [comment]
![projects](https://cloud.githubusercontent.com/assets/21959358/18684606/c8522138-7f42-11e6-9186-597714556a93.png)

**Comment by robmyre** [comment]
![code_of_conduct](https://cloud.githubusercontent.com/assets/21959358/18682103/f64c8704-7f38-11e6-82a8-79ba79012c77.jpg)

**Comment by robmyre** [comment]
![acceptable_licenses](https://cloud.githubusercontent.com/assets/21959358/18682447/3e290e0c-7f3a-11e6-8a4b-7324476a0fe6.png)
![dig_ad_proxy](https://cloud.githubusercontent.com/assets/21959358/18682448/3e2e97aa-7f3a-11e6-8d1c-6d54370f5e1e.png)

**Comment by robmyre** [comment]
![onboard_wiki](https://cloud.githubusercontent.com/assets/21959358/18682596/e7d93e68-7f3a-11e6-99a8-c580e38dbbb7.png)

**Comment by robmyre** [comment]
![rvertica](https://cloud.githubusercontent.com/assets/21959358/18682710/471e3644-7f3b-11e6-805c-1a90becf7cd4.png)

**Comment by robmyre** [comment]
![mobilequizzes](https://cloud.githubusercontent.com/assets/21959358/18682850/cbb5a04a-7f3b-11e6-8bf5-705a41bf987e.PNG)

**Comment by robmyre** [comment]
![donations](https://cloud.githubusercontent.com/assets/21959358/18682902/0e60aa20-7f3c-11e6-8278-fa9824a8f649.png)

**Comment by robmyre** [comment]
![visualize_voter](https://cloud.githubusercontent.com/assets/21959358/18683040/9db03dc6-7f3c-11e6-9c49-231c7ca22aa9.png)

**Comment by robmyre** [comment]
![donations](https://cloud.githubusercontent.com/assets/21959358/18683099/d9c8e2d6-7f3c-11e6-9bed-ef1cf8f922aa.png)

**Comment by robmyre** [comment]
![candidate_bot](https://cloud.githubusercontent.com/assets/21959358/18683191/2877f2d2-7f3d-11e6-991a-1e84af957092.png)

**Comment by robmyre** [comment]
![openopportunities](https://cloud.githubusercontent.com/assets/21959358/18683360/eb004a34-7f3d-11e6-89d1-f2a71e63f965.png)

**Comment by jillh510** [comment]
Looks like the images are all in - can this issue be closed?

**Comment by rschroed** [comment]
I think so!
